### ISSUE TITLE
Color Rings From Overlay Broken?

### ISSUE THREAD

**Issue by ayzenbergd** [CMAlbrecht/ChainmailleDesigner#8]
The Color Rings From Overlay feature seems to do nothing. The pop-up window opens with a drop-down for the palette and sliders for Color Matching. Nothing show up in the Preview Box and clicking OK does nothing.

**Comment by CMAlbrecht** [comment]
This is a valid issue. The event handler for the selected item changed event of the palette section combo box in the ColorFromOverlayForm was inadvertently disconnected.  This resulted in a null palette section no matter what action the user was able to take.  Without a selected palette section, no palette colors could be applied to the rings of the design.

Re-connecting the event handler will allow the main design to be colored according to the overlay.  This is a quick and easy fix, the efficacy of which I have already tested.

A secondary issue is that although there is now a preview pane on the form, nothing is being done to make use of it.  That's going to be a more complicated fix, if we decide to retain the preview panel, because ring coloring from an overlay image was only defined for the base design class.  Possibly we would have to clone the entire design, then color the clone, and use the clone for rendering the preview image.  Somewhat more involved, but less clumsy, would be to provide an alternate rendering method to the design class that allowed a different color image to be used for the design on a temporary one-time basis (i.e. the alternate color image would not become a member of the design, but would remain a local property of the ColorFromOverlayForm).
